name: zipstream
base: core18
version: '0.4.3'
summary: Easily share files and directories over the network
description: |
  A command line tool that allows you to easily share files and directories
  over the network.

grade: stable
confinement: classic # strict
architectures: [amd64]

apps:
  zipstream:
    command: bin/zipstream
    # plugs:
    #   - network
    #   - network-bind
    #   - removable-media

parts:
  zipstream:
    source: ./
    plugin: crystal
    build-packages:
     - git
     - libssl-dev
